package codingproblems.leetcode;

/*
 * 389. Find the Difference
 * Easy Topics
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
 */
public class Problem389 {
    public char findTheDifference(String s, String t) {
        int[] charCount = new int[26];
        for (char c : s.toCharArray())
            charCount[c - 'a']++;
        for (char c : t.toCharArray())
            charCount[c - 'a']--;
        for (int i = 0; i < 26; i++)
            if (charCount[i] != 0)
                return (char) (i + 'a');

        return ' ';

        // StringBuilder result = new StringBuilder(t);
        // for (char c : s.toCharArray()) {
        // int index = result.indexOf(String.valueOf(c));
        // result.deleteCharAt(index);
        // }
        // return result.charAt(0);
    }
}
